task:
  - name: mqtt-python
    init: |
      sudo apt update
      sudo apt install mosquitto mosquitto-clients -y
      



ports:
  - port: 1883
    onOpen: ignore
    visibility: public
  - port: 8083
    onOpen: ignore
  - port: 443
    onOpen: ignore
    visibility: public
